import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from 'next/image';
import linkedin from "../public/linkedin.jpeg";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/weather-dashboard.png";
import web2 from "../public/budget-tracker.png";
import web3 from "../public/coding-quiz.png";
import web4 from "../public/workday-scheduler.png";
import web5 from "../public/password-generator.png";
import { useState } from "react";
import Carousel from "react-bootstrap-carousel";
import "react-bootstrap-carousel/dist/react-bootstrap-carousel.css";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Brahm Gicheru Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">

       <section className="min-h-screen">
         <nav className="py-10 mb-12 flex justify-between">
        <h1 className="text-xl font-burtons dark:text-white">Brahm Gicheru</h1>
        <ul className="flex items-center">
          <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl dark:fill-white"/>
          </li>
          <li>
            <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-black px-4 py-2 rounded-md ml-8 dark:text-white" href="https://drive.google.com/file/d/18HPh9s5Yf5A5bcCHFFk9TsoBZNRKoGHH/view?usp=sharing">Resume</a>
          </li>
        </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl" >Brahm Gicheru</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Software Engineer</h3>
            <p className="text-md text-justify py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
            Hello, my name is Brahm and I am a government contractor with 9+ years of experience looking to transition into software engineering. I have completed projects using technologies such as <span className="text-teal-500">JavaScript, React, Node, Express, HTML, CSS, JSON, MySQL, MongoDB, and APIs </span> in school and in my personal time, and I am always looking for ways to expand my knowledge and expertise. I am eager to take on new challenges and make a meaningful contribution to the field as a professional software engineer.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 dark:text-white">
            <a href="https://www.linkedin.com/in/brahm-gicheru-5b75144b/">
            <AiFillLinkedin />
            </a>
            {/* <AiFillGithub /> */}
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={linkedin} layout="fill" objectFit="cover"/>
          </div>
       </section>
       
       {/* <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-lg font-medium py-2 leading-8 text-gray-800 dark:text-white"> <span className="text-teal-500">Filler </span> Text</p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image className="" src={design} width={100} height={100} className="m-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating designs blah....</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} className="m-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating designs blah....</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} className="m-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating designs blah....</p>
            </div>

          </div>
       </section> */}

       <section>
         <div>
           <h3 className="text-5xl py-1 dark:text-white">Portfolio</h3>
           {/* <p className="text-lg font-medium py-2 leading-8 text-gray-800 dark:text-white">Here is my portfolio..........</p> */}
         </div>

         <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
           <div className="basis-1/3 flex-1">
           <a href="https://brahmg1.github.io/weather-dashboard/Develop/index.html" target="_blank">
           <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
                    </a>
                    <h3  className="text-lg font-medium pt-8 pb-2 dark:text-white">Weather Dashboard</h3>
           </div>

           <div className="basis-1/3 flex-1">
           <a href="https://infinite-reef-10985.herokuapp.com/" target="_blank">
           <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
                    </a>
                    <h3  className="text-lg font-medium pt-8 pb-2 dark:text-white">Budget Tracker</h3>
           </div>

           <div className="basis-1/3 flex-1">
           <a href="https://brahmg1.github.io/code-quiz/Develop/index.html" target="_blank">
           <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
                    </a>
                    <h3  className="text-lg font-medium pt-8 pb-2 dark:text-white">Coding Quiz</h3>
           </div>

           <div className="basis-1/3 flex-1">
           <a href="https://brahmg1.github.io/super-disco/Develop/index.html" target="_blank">
           <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
                    </a>
                    <h3  className="text-lg font-medium pt-8 pb-2 dark:text-white">Work Day Scheduler</h3>
           </div>

           <div className="basis-1/3 flex-1">
           <a href="https://brahmg1.github.io/password-generator/Develop/index.html" target="_blank">
           <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
                    </a>
                    <h3  className="text-lg font-medium pt-8 pb-2 dark:text-white">Password Generator</h3>
           </div>

         </div>

       </section>

      </main>

      </div>
      
  )
}
